[package]
name = "yudi_shell"
version = "0.1.0"
authors = ["Yudi Yang <yyang116@u.rochester.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
